package org.liteorm.example;

import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.liteorm.DefaultSqlEngine;
import org.liteorm.JdbcConnectionProvider;
import org.liteorm.runtime.ExecutionProcessor;
import org.liteorm.runtime.ParameterProcessor;
import org.liteorm.runtime.ResultProcessor;
import org.liteorm.runtime.SqlProcessor;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.util.List;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;

class UserMapperE2ETest {

    private JdbcDataSource dataSource;
    private UserMapper annotationMapper;
    private UserXmlMapper xmlMapper;
    private UserMetadataMapper metadataMapper;
    private GeneratedKeyMapperFixture generatedKeyMapper;
    private SingleResultMapperFixture singleResultMapper;
    private JdbcTypeMapperFixture jdbcTypeMapper;
    private UserMapper auditedMapper;
    private List<String> auditEvents;

    @BeforeEach
    void setUp() throws Exception {
        dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:liteorm-example;DB_CLOSE_DELAY=-1");

        try (Connection connection = dataSource.getConnection(); Statement statement = connection.createStatement()) {
            statement.execute("DROP TABLE IF EXISTS users");
            statement.execute("CREATE TABLE users (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "name VARCHAR(100), email VARCHAR(200), age INT)");
            statement.execute("DROP TABLE IF EXISTS user_metadata");
            statement.execute("CREATE TABLE user_metadata (user_id BIGINT PRIMARY KEY, payload VARCHAR(500))");
            statement.execute("DROP TABLE IF EXISTS jdbc_types");
            statement.execute("CREATE TABLE jdbc_types (id BIGINT PRIMARY KEY, quantity INT, "
                + "amount DECIMAL(18, 2), business_date DATE, created_at TIMESTAMP, "
                + "occurred_at TIMESTAMP WITH TIME ZONE, status VARCHAR(20), payload VARBINARY, enabled BOOLEAN, "
                + "required_count BIGINT NOT NULL, required_quantity INT NOT NULL, small_value SMALLINT NOT NULL, "
                + "tiny_value TINYINT NOT NULL, ratio DOUBLE NOT NULL, score REAL NOT NULL, "
                + "required_enabled BOOLEAN NOT NULL, code CHAR(1) NOT NULL)");
        }

        JdbcConnectionProvider connectionProvider = new JdbcConnectionProvider(dataSource);
        annotationMapper = new UserMapperImpl(connectionProvider);
        xmlMapper = new UserXmlMapperImpl(connectionProvider);
        metadataMapper = new UserMetadataMapperImpl(connectionProvider);
        generatedKeyMapper = new GeneratedKeyMapperFixtureImpl(connectionProvider);
        singleResultMapper = new SingleResultMapperFixtureImpl(connectionProvider);
        jdbcTypeMapper = new JdbcTypeMapperFixtureImpl(connectionProvider);
        auditEvents = new java.util.ArrayList<>();
        MigrationAuditInterceptor firstAuditInterceptor = new MigrationAuditInterceptor("first", auditEvents);
        MigrationAuditInterceptor secondAuditInterceptor = new MigrationAuditInterceptor("second", auditEvents);
        List<SqlProcessor> processors = List.of(
            new ParameterProcessor(),
            new ExecutionProcessor(),
            new ResultProcessor()
        );
        auditedMapper = new UserMapperImpl(new DefaultSqlEngine(
            connectionProvider,
            processors,
            List.of(firstAuditInterceptor, secondAuditInterceptor)
        ));
    }

    @Test
    void generatedKeyInsertReturnsIdentityThatResolvesTheInsertedRow() {
        Long id = generatedKeyMapper.insert("Generated", "generated@example.com", 27);

        assertEquals(new User(id, "Generated", "generated@example.com", 27), annotationMapper.findById(id));
    }

    @Test
    void singleResultMethodRejectsMoreThanOneRow() {
        annotationMapper.insert(1L, "Alice", "alice@example.com", 30);
        annotationMapper.insert(2L, "Bob", "bob@example.com", 28);

        RuntimeException failure = assertThrows(RuntimeException.class, singleResultMapper::findName);

        assertEquals("org.liteorm.api.NonUniqueResultException", failure.getClass().getName());
        assertEquals(
            "Expected at most one row for org.liteorm.example.SingleResultMapperFixture.findName but found 2",
            failure.getMessage()
        );
    }

    @Test
    void generatedMapperConvertsCommonJdbcTypesAndPreservesSqlNulls() throws Exception {
        Instant occurredAt = Instant.parse("2026-08-14T01:23:45Z");
        try (Connection connection = dataSource.getConnection();
             PreparedStatement statement = connection.prepareStatement(
                 "INSERT INTO jdbc_types VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)")) {
            statement.setLong(1, 1L);
            statement.setInt(2, 7);
            statement.setBigDecimal(3, new BigDecimal("123.45"));
            statement.setObject(4, LocalDate.of(2026, 8, 14));
            statement.setObject(5, LocalDateTime.of(2026, 8, 14, 9, 30));
            statement.setObject(6, OffsetDateTime.ofInstant(occurredAt, ZoneOffset.UTC));
            statement.setString(7, JdbcStatus.ACTIVE.name());
            statement.setBytes(8, new byte[]{1, 2, 3});
            statement.setBoolean(9, true);
            statement.setLong(10, 99L);
            statement.setInt(11, 8);
            statement.setShort(12, (short) 6);
            statement.setByte(13, (byte) 4);
            statement.setDouble(14, 1.5D);
            statement.setFloat(15, 2.5F);
            statement.setBoolean(16, true);
            statement.setString(17, "Z");
            statement.executeUpdate();

            statement.setLong(1, 2L);
            for (int index = 2; index <= 9; index++) {
                statement.setObject(index, null);
            }
            statement.setLong(10, 0L);
            statement.setInt(11, 0);
            statement.setShort(12, (short) 0);
            statement.setByte(13, (byte) 0);
            statement.setDouble(14, 0D);
            statement.setFloat(15, 0F);
            statement.setBoolean(16, false);
            statement.setString(17, "N");
            statement.executeUpdate();
        }

        JdbcTypesRow populated = jdbcTypeMapper.findById(1L);
        assertEquals(1L, populated.id());
        assertEquals(7, populated.quantity());
        assertEquals(new BigDecimal("123.45"), populated.amount());
        assertEquals(LocalDate.of(2026, 8, 14), populated.businessDate());
        assertEquals(LocalDateTime.of(2026, 8, 14, 9, 30), populated.createdAt());
        assertEquals(occurredAt, populated.occurredAt());
        assertEquals(JdbcStatus.ACTIVE, populated.status());
        assertArrayEquals(new byte[]{1, 2, 3}, populated.payload());
        assertEquals(true, populated.enabled());
        assertEquals(99L, populated.requiredCount());
        assertEquals(8, populated.requiredQuantity());
        assertEquals((short) 6, populated.smallValue());
        assertEquals((byte) 4, populated.tinyValue());
        assertEquals(1.5D, populated.ratio());
        assertEquals(2.5F, populated.score());
        assertEquals(true, populated.requiredEnabled());
        assertEquals('Z', populated.code());

        JdbcTypesRow nullable = jdbcTypeMapper.findById(2L);
        assertEquals(2L, nullable.id());
        assertNull(nullable.quantity());
        assertNull(nullable.amount());
        assertNull(nullable.businessDate());
        assertNull(nullable.createdAt());
        assertNull(nullable.occurredAt());
        assertNull(nullable.status());
        assertNull(nullable.payload());
        assertNull(nullable.enabled());
        assertEquals(0L, nullable.requiredCount());
        assertEquals(0, nullable.requiredQuantity());
        assertEquals((short) 0, nullable.smallValue());
        assertEquals((byte) 0, nullable.tinyValue());
        assertEquals(0D, nullable.ratio());
        assertEquals(0F, nullable.score());
        assertEquals(false, nullable.requiredEnabled());
        assertEquals('N', nullable.code());
    }

    @Test
    void generatedAnnotationAndXmlMappersExecuteCrudAgainstH2() {
        assertEquals(1, annotationMapper.insert(1L, "Alice", "alice@example.com", 30));
        assertEquals(new User(1L, "Alice", "alice@example.com", 30), annotationMapper.findById(1L));
        assertEquals(new User(1L, "Alice", "alice@example.com", 30), xmlMapper.findByEmail("alice@example.com"));

        assertEquals(1, annotationMapper.update(1L, "Alice Zhang", "alice.zhang@example.com", 31));
        assertEquals(new User(1L, "Alice Zhang", "alice.zhang@example.com", 31), annotationMapper.findById(1L));

        assertEquals(1, annotationMapper.deleteById(1L));
        assertNull(annotationMapper.findById(1L));
    }

    @Test
    void generatedAnnotationMapperExecutesRealJdbcBatch() {
        int[] counts = annotationMapper.insertBatch(List.of(
            new User(10L, "Dora", "dora@example.com", 25),
            new User(11L, "Evan", "evan@example.com", 27)
        ));

        assertArrayEquals(new int[]{1, 1}, counts);
        assertEquals(new User(10L, "Dora", "dora@example.com", 25), annotationMapper.findById(10L));
        assertEquals(new User(11L, "Evan", "evan@example.com", 27), annotationMapper.findById(11L));
    }

    @Test
    void generatedXmlMapperExecutesRealJdbcBatch() {
        int[] counts = xmlMapper.insertBatch(List.of(
            new User(12L, "Faye", "faye@example.com", 29),
            new User(13L, "Gabe", "gabe@example.com", 31)
        ));

        assertArrayEquals(new int[]{1, 1}, counts);
        assertEquals(new User(12L, "Faye", "faye@example.com", 29), annotationMapper.findById(12L));
        assertEquals(new User(13L, "Gabe", "gabe@example.com", 31), annotationMapper.findById(13L));
    }

    @Test
    void concurrentBatchCallsKeepParameterSetsIsolated() throws Exception {
        try (var executor = Executors.newFixedThreadPool(2)) {
            var first = executor.submit(() -> annotationMapper.insertBatch(List.of(
                new User(20L, "Hana", "hana@example.com", 24),
                new User(21L, "Ivan", "ivan@example.com", 26)
            )));
            var second = executor.submit(() -> annotationMapper.insertBatch(List.of(
                new User(30L, "Jade", "jade@example.com", 32),
                new User(31L, "Kyle", "kyle@example.com", 34)
            )));

            assertArrayEquals(new int[]{1, 1}, first.get(5, TimeUnit.SECONDS));
            assertArrayEquals(new int[]{1, 1}, second.get(5, TimeUnit.SECONDS));
        }

        assertEquals(List.of("Hana", "Ivan", "Jade", "Kyle"), annotationMapper.findAllNames());
    }

    @Test
    void xmlForeachPreservesParameterOrderAndOmitsEmptyCollectionCondition() {
        annotationMapper.insert(1L, "Alice", "alice@example.com", 30);
        annotationMapper.insert(2L, "Bob", "bob@example.com", 28);
        annotationMapper.insert(3L, "Carol", "carol@example.com", 35);

        assertEquals(
            List.of(
                new User(1L, "Alice", "alice@example.com", 30),
                new User(3L, "Carol", "carol@example.com", 35)
            ),
            xmlMapper.findByIds(List.of(1L, 3L))
        );
        assertEquals(3, xmlMapper.findByIds(List.of()).size());
        assertEquals(3, xmlMapper.findByIds(null).size());
    }

    @Test
    void xmlNestedDynamicTagsPreserveScopeWhitespaceAndParameterOrder() {
        annotationMapper.insert(1L, "Alice", "alice@example.com", 30);
        annotationMapper.insert(2L, "Bob", "bob@example.com", 25);
        annotationMapper.insert(3L, "Alicia", "alicia@example.com", 40);
        annotationMapper.insert(4L, "Carol", "carol@example.com", 35);

        assertEquals(
            List.of(
                new User(1L, "Alice", "alice@example.com", 30),
                new User(3L, "Alicia", "alicia@example.com", 40)
            ),
            xmlMapper.searchAdvanced("Ali", 100, List.of(1L, 3L, 4L))
        );
        assertEquals(
            List.of(
                new User(3L, "Alicia", "alicia@example.com", 40),
                new User(4L, "Carol", "carol@example.com", 35)
            ),
            xmlMapper.searchAdvanced(null, 35, List.of())
        );
        assertEquals(4, xmlMapper.searchAdvanced(null, null, null).size());
    }

    @Test
    void xmlSetPreservesParameterOrderWhenOptionalAssignmentsAreSkipped() {
        annotationMapper.insert(1L, "Alice", "alice@example.com", 30);

        assertEquals(
            1,
            xmlMapper.updateSelective(new User(1L, null, "updated@example.com", 31))
        );
        assertEquals(
            new User(1L, "Alice", "updated@example.com", 31),
            annotationMapper.findById(1L)
        );
    }

    @Test
    void generatedMapperMapsScalarAndScalarListResults() {
        annotationMapper.insert(1L, "Alice", "alice@example.com", 30);
        annotationMapper.insert(2L, "Bob", "bob@example.com", 28);

        assertEquals("Alice", annotationMapper.findNameById(1L));
        assertEquals(2L, annotationMapper.countUsers());
        assertEquals(List.of("Alice", "Bob"), annotationMapper.findAllNames());
    }

    @Test
    void generatedMapperMapsJavaBeansThroughNoArgConstructorAndSetters() {
        annotationMapper.insert(1L, "Alice", "alice@example.com", 30);
        annotationMapper.insert(2L, "Bob", "bob@example.com", 28);

        assertUserBean(annotationMapper.findBeanById(1L), 1L, "Alice", "alice@example.com", 30);

        List<UserBean> users = annotationMapper.findAllBeans();
        assertEquals(2, users.size());
        assertUserBean(users.get(0), 1L, "Alice", "alice@example.com", 30);
        assertUserBean(users.get(1), 2L, "Bob", "bob@example.com", 28);
    }

    @Test
    void generatedMapperUsesDocumentedEmptyResultSemantics() {
        assertNull(annotationMapper.findNameById(999L));
        assertNull(annotationMapper.findById(999L));
        assertNull(annotationMapper.findBeanById(999L));
        assertEquals(List.of(), annotationMapper.findAllNames());
        assertEquals(List.of(), annotationMapper.findAllBeans());
    }

    @Test
    void generatedMapperCallsCompileTimeBoundSqlProvider() {
        annotationMapper.insert(1L, "Alice", "alice@example.com", 30);
        annotationMapper.insert(2L, "Bob", "bob@example.com", 28);
        annotationMapper.insert(3L, "Alfred", "alfred@example.com", 35);

        assertEquals(
            List.of(
                new User(3L, "Alfred", "alfred@example.com", 35),
                new User(1L, "Alice", "alice@example.com", 30)
            ),
            annotationMapper.search(new UserSearch("Al", true))
        );
        assertEquals(3, annotationMapper.search(new UserSearch(null, false)).size());
    }

    @Test
    void generatedMapperCallsCustomBinderAndRowMapperDirectly() {
        JsonValue blue = new JsonValue("{\"theme\":\"blue\"}");
        JsonValue red = new JsonValue("{\"theme\":\"red\"}");

        assertEquals(1, metadataMapper.insert(1L, blue));
        assertEquals(1, metadataMapper.insert(2L, red));
        assertEquals(1, metadataMapper.insert(3L, blue));
        assertEquals(1, metadataMapper.insert(4L, null));

        assertEquals(
            List.of(new UserMetadata(1L, blue), new UserMetadata(3L, blue)),
            metadataMapper.findByPayload(blue)
        );
        assertEquals(
            List.of(new UserMetadata(1L, blue), new UserMetadata(3L, blue)),
            metadataMapper.findByPayloadDynamically(blue)
        );
        assertEquals(new UserMetadata(2L, red), metadataMapper.findByUserId(2L));
        assertEquals(new UserMetadata(4L, new JsonValue(null)), metadataMapper.findByUserId(4L));
        assertNull(metadataMapper.findByUserId(999L));
    }

    @Test
    void interceptorObservesGeneratedMapperWithoutChangingDispatch() {
        assertEquals(1, auditedMapper.insert(10L, "Audit", "audit@example.com", 40));

        assertEquals(
            List.of(
                "first:before:org.liteorm.example.UserMapper.insert",
                "second:before:org.liteorm.example.UserMapper.insert",
                "second:success:org.liteorm.example.UserMapper.insert:1",
                "first:success:org.liteorm.example.UserMapper.insert:1"
            ),
            auditEvents
        );
    }

    private void assertUserBean(UserBean user, Long id, String name, String email, Integer age) {
        assertEquals(id, user.getId());
        assertEquals(name, user.getName());
        assertEquals(email, user.getEmail());
        assertEquals(age, user.getAge());
    }
}
