package io.github.lynxus.test.database;

import io.github.lynxus.testsupport.database.DatabaseEngine;

class PostgresCompatibilityTest extends AbstractDatabaseCompatibilityTest {

    @Override
    protected DatabaseEngine databaseEngine() {
        return DatabaseEngine.POSTGRESQL;
    }

    @Override
    protected String identityDefinition() {
        return "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";
    }

    @Override
    protected String binaryDefinition() {
        return "BYTEA";
    }

    @Override
    protected String uuidDefinition() {
        return "VARCHAR(36)";
    }

    @Override
    protected String localTimeDefinition() {
        return "TIME(6)";
    }

    @Override
    protected String offsetDateTimeDefinition() {
        return "TIMESTAMP(6) WITH TIME ZONE";
    }

    @Override
    protected String nationalCharDefinition() {
        return "VARCHAR(16)";
    }

    @Override
    protected String nationalVarcharDefinition() {
        return "VARCHAR(64)";
    }

    @Override
    protected String sleepSql() {
        return "SELECT pg_sleep(3)";
    }
}
