package ${packageName};

import org.liteorm.api.*;
import org.liteorm.DefaultSqlEngine;
import java.util.List;
import java.util.ArrayList;

/**
 * Generated MapperImpl - Zero Reflection
 * 编译期生成的硬编码实现，无任何反射调用
 * 
 * Generated by LiteORM at ${.now}
 */
public class ${className} implements ${interfaceName} {

    private final SqlEngine sqlEngine;

    public ${className}(ConnectionManager connectionManager) {
        this.sqlEngine = new DefaultSqlEngine(connectionManager);
    }

<#list methods as method>
    @Override
    public ${method.returnType} ${method.name}(${method.parameterList}) {
    <#if method.sqlInfo??>
        // 硬编码SQL模板 - 编译期确定，保持#{param}语法
        String sqlTemplate = "${method.sqlInfo.processedSql}";
        
        // 硬编码参数映射 - 零反射，编译期确定参数绑定
        <#if method.parameters?has_content>
        java.util.Map<String, Object> paramMap = new java.util.HashMap<>();
        <#list method.parameters as param>
        paramMap.put("${param.name}", ${param.bindingCode});
        </#list>
        <#else>
        java.util.Map<String, Object> paramMap = new java.util.HashMap<>();
        </#if>
        
        // 创建SQL执行任务 - 使用#{param}语法和参数映射
        SqlTask task = new SqlTask(sqlTemplate, paramMap, SqlTask.SqlType.${method.sqlInfo.type}, ${method.sqlInfo.requiresTransaction?c});
        
        // 执行SQL - 通过责任链处理
        SqlResult result = sqlEngine.execute(task);
        
        // 统一错误检查 - 物理必需：异常处理
        if (result.hasError()) {
            throw new RuntimeException(result.getException());
        }
        
        // 硬编码结果映射 - 零反射
        <#if method.sqlInfo.type == "SELECT">
        <#if method.returnType?contains("List")>
        // 硬编码List映射 - 零反射，编译期确定
        List<Object[]> rows = result.getQueryResults();
        List<${method.elementType}> resultList = new ArrayList<>(rows.size());
        for (Object[] row : rows) {
            resultList.add(${method.objectMapping});
        }
        return resultList;
        <#elseif method.returnType != "void">
        // 硬编码单对象映射 - 零反射，编译期确定
        List<Object[]> rows = result.getQueryResults();
        if (rows.isEmpty()) {
            return null;
        }
        Object[] row = rows.get(0);
        return ${method.objectMapping};
        </#if>
        <#else>
        // INSERT/UPDATE/DELETE返回影响行数
        return result.getUpdateCount();
        </#if>
    <#else>
        throw new UnsupportedOperationException("No SQL annotation found for method: ${method.name}");
    </#if>
    }

</#list>
}
