package org.liteorm.test.database;

import org.postgresql.ds.PGSimpleDataSource;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import org.testcontainers.utility.DockerImageName;

import javax.sql.DataSource;

@Testcontainers(disabledWithoutDocker = true)
class PostgresCompatibilityTest extends AbstractDatabaseCompatibilityTest {

    @Container
    private static final PostgreSQLContainer<?> DATABASE = new PostgreSQLContainer<>(
        DockerImageName.parse("postgres:16.4-alpine"));

    @Override
    protected DataSource dataSource() {
        PGSimpleDataSource dataSource = new PGSimpleDataSource();
        dataSource.setURL(DATABASE.getJdbcUrl());
        dataSource.setUser(DATABASE.getUsername());
        dataSource.setPassword(DATABASE.getPassword());
        return dataSource;
    }

    @Override
    protected String identityDefinition() {
        return "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";
    }

    @Override
    protected String binaryDefinition() {
        return "BYTEA";
    }

    @Override
    protected String sleepSql() {
        return "SELECT pg_sleep(3)";
    }
}
