package ${packageName};

import org.liteorm.api.*;
import org.liteorm.DefaultSqlEngine;
import org.liteorm.runtime.*;
import org.liteorm.api.BoundSql;
import org.liteorm.api.ParameterBinder;
import java.util.List;
import java.util.ArrayList;

/**
 * Generated MapperImpl - Zero Reflection
 * 编译期生成的硬编码实现，无任何反射调用
 * 
 * Generated by LiteORM at ${.now}
 */
public class ${implClassName} implements ${interfaceName} {

    private final SqlEngine sqlEngine;

    public ${implClassName}(SqlEngine sqlEngine) {
        this.sqlEngine = java.util.Objects.requireNonNull(sqlEngine, "sqlEngine");
    }

    public ${implClassName}(ConnectionManager connectionManager) {
        // 创建默认的责任链处理器
        List<SqlProcessor> processors = new ArrayList<>();
        org.liteorm.DefaultTransactionManager transactionManager = 
            new org.liteorm.DefaultTransactionManager(connectionManager);
        processors.add(new ConnectionProcessor(connectionManager));
        processors.add(new TransactionProcessor(transactionManager));
        processors.add(new ParameterProcessor());
        processors.add(new ExecutionProcessor());
        processors.add(new ResultProcessor());
        
        this.sqlEngine = new DefaultSqlEngine(connectionManager, processors);
    }

${generatedMethods}

    private void appendSqlFragment(StringBuilder sql, String fragment) {
        if (fragment == null || fragment.isBlank()) {
            return;
        }
        String normalized = fragment.trim();
        if (!sql.isEmpty() && needsSqlSeparator(sql.charAt(sql.length() - 1), normalized.charAt(0))) {
            sql.append(' ');
        }
        sql.append(normalized);
    }

    private boolean needsSqlSeparator(char previous, char next) {
        return !Character.isWhitespace(previous)
            && !Character.isWhitespace(next)
            && previous != '('
            && next != ')'
            && next != ','
            && previous != ',';
    }

    private String normalizeWhereClause(String rawClause) {
        String normalized = rawClause == null ? "" : rawClause.trim();
        normalized = normalized.replaceFirst("^(?i)(AND|OR)\\s+", "");
        return normalized.trim();
    }

    private String normalizeSetClause(String rawClause) {
        String normalized = rawClause == null ? "" : rawClause.trim();
        while (normalized.endsWith(",")) {
            normalized = normalized.substring(0, normalized.length() - 1).trim();
        }
        return normalized;
    }

    private String applyTrim(String rawClause, String prefix, String suffix, String prefixOverrides, String suffixOverrides) {
        String normalized = rawClause == null ? "" : rawClause.trim();
        normalized = stripOverrides(normalized, prefixOverrides, true);
        normalized = stripOverrides(normalized, suffixOverrides, false);
        if (normalized.isBlank()) {
            return "";
        }
        StringBuilder builder = new StringBuilder();
        if (prefix != null && !prefix.isBlank()) {
            builder.append(prefix.trim()).append(" ");
        }
        builder.append(normalized);
        if (suffix != null && !suffix.isBlank()) {
            builder.append(" ").append(suffix.trim());
        }
        return builder.toString();
    }

    private String stripOverrides(String clause, String overrides, boolean prefix) {
        if (overrides == null || overrides.isBlank()) {
            return clause == null ? "" : clause.trim();
        }
        String normalized = clause == null ? "" : clause.trim();
        for (String token : overrides.split("\\|")) {
            String trimmed = token.trim();
            if (trimmed.isEmpty()) {
                continue;
            }
            if (prefix && normalized.regionMatches(true, 0, trimmed, 0, trimmed.length())) {
                normalized = normalized.substring(trimmed.length()).trim();
            }
            if (!prefix && normalized.length() >= trimmed.length()
                && normalized.regionMatches(true, normalized.length() - trimmed.length(), trimmed, 0, trimmed.length())) {
                normalized = normalized.substring(0, normalized.length() - trimmed.length()).trim();
            }
        }
        return normalized;
    }
}
