package org.liteorm.test;

import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.liteorm.LiteOrm;
import org.liteorm.annotation.Column;
import org.liteorm.annotation.Insert;
import org.liteorm.annotation.Mapper;
import org.liteorm.annotation.Param;
import org.liteorm.annotation.Select;
import org.liteorm.runtime.ResultValueConverters;

import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;

class JdbcTypeRuntimeTest {

    private JdbcTypeRuntimeMapper mapper;

    @BeforeEach
    void createDatabase() throws SQLException {
        JdbcDataSource dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:" + UUID.randomUUID() + ";DB_CLOSE_DELAY=-1");
        try (var connection = dataSource.getConnection();
             var statement = connection.createStatement()) {
            statement.execute("""
                CREATE TABLE jdbc_types (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    uuid_value UUID,
                    local_time_value TIME(6),
                    offset_date_time_value TIMESTAMP(6) WITH TIME ZONE
                )
                """);
        }
        mapper = new JdbcTypeRuntimeMapperImpl(LiteOrm.jdbc(dataSource).build().sqlExecutor());
    }

    @Test
    void roundTripsFrozenJdbcTypesThroughGeneratedMapper() {
        UUID uuid = UUID.fromString("123e4567-e89b-12d3-a456-426614174000");
        LocalTime localTime = LocalTime.of(12, 34, 56, 123_456_000);
        OffsetDateTime offsetDateTime = OffsetDateTime.of(
            2026, 8, 31, 12, 34, 56, 654_321_000, ZoneOffset.ofHours(8));

        assertEquals(1, mapper.insert(uuid, localTime, offsetDateTime));
        JdbcTypeRuntimeRow actual = mapper.find(1L);

        assertEquals(uuid, actual.uuid());
        assertEquals(localTime, actual.localTime());
        assertEquals(offsetDateTime.toInstant(), actual.offsetDateTime().toInstant());
        assertEquals(uuid, mapper.findUuid(1L));
        assertEquals(localTime, mapper.findLocalTime(1L));
        assertEquals(offsetDateTime.toInstant(), mapper.findOffsetDateTime(1L).toInstant());
    }

    @Test
    void preservesNullFrozenJdbcTypes() {
        assertEquals(1, mapper.insert(null, null, null));
        JdbcTypeRuntimeRow actual = mapper.find(1L);

        assertNull(actual.uuid());
        assertNull(actual.localTime());
        assertNull(actual.offsetDateTime());
        assertNull(mapper.findUuid(1L));
        assertNull(mapper.findLocalTime(1L));
        assertNull(mapper.findOffsetDateTime(1L));
    }

    @Test
    void rejectsOffsetDateTimeConversionWithoutInstantOrOffset() {
        assertThrows(IllegalArgumentException.class, () ->
            ResultValueConverters.toOffsetDateTime(LocalDateTime.of(2026, 8, 31, 12, 34, 56)));
    }
}

@Mapper
interface JdbcTypeRuntimeMapper {

    @Insert("INSERT INTO jdbc_types (uuid_value, local_time_value, offset_date_time_value) "
        + "VALUES (#{uuid}, #{localTime}, #{offsetDateTime})")
    int insert(
        @Param("uuid") UUID uuid,
        @Param("localTime") LocalTime localTime,
        @Param("offsetDateTime") OffsetDateTime offsetDateTime);

    @Select("SELECT uuid_value, local_time_value, offset_date_time_value FROM jdbc_types WHERE id = #{id}")
    JdbcTypeRuntimeRow find(@Param("id") Long id);

    @Select("SELECT uuid_value FROM jdbc_types WHERE id = #{id}")
    UUID findUuid(@Param("id") Long id);

    @Select("SELECT local_time_value FROM jdbc_types WHERE id = #{id}")
    LocalTime findLocalTime(@Param("id") Long id);

    @Select("SELECT offset_date_time_value FROM jdbc_types WHERE id = #{id}")
    OffsetDateTime findOffsetDateTime(@Param("id") Long id);
}

record JdbcTypeRuntimeRow(
    @Column("uuid_value") UUID uuid,
    @Column("local_time_value") LocalTime localTime,
    @Column("offset_date_time_value") OffsetDateTime offsetDateTime) {
}
